services:
  example.web:
    image: ${DOCKER_REGISTRY-}exampleweb
    container_name: example.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
      - ./angular.json:/app/angular.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./package.json:/app/package.json:ro
      - /app/node_modules
    networks:
      - backend_examplenetwork

networks:
  backend_examplenetwork:
    external: true
    name: backend_examplenetwork