services:
  example.api:
    image: ${DOCKER_REGISTRY-}exampleapi
    container_name: example.api
    build:
      context: .
      dockerfile: Example.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - example.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - SA_PASSWORD=${SA_PASSWORD}
      - ConnectionStrings__DefaultConnection=Server=example.database;Database=ExampleDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;
    networks:
      - examplenetwork
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  example.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: example.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - examplenetwork

volumes:
  sqldata:
  
networks:
  examplenetwork:    